- name: Deploy application container
  hosts: app_server
  become: yes

  tasks:
    - name: Pull latest app image
      docker_image:
        name: swat7928/learning-app
        tag: latest
        source: pull

    - name: Stop existing container if running
      docker_container:
        name: learning-app
        state: absent
      ignore_errors: yes

    - name: Run application container
      docker_container:
        name: learning-app
        image: swat7928/learning-app:latest
        ports:
          - "80:5000"
        restart_policy: always
